### ISSUE TITLE
Add "chores" to release notes

### ISSUE THREAD

**Issue by davidhouweling** [trainline/webpack-bundle-delta#10]
At present chores are not part of release notes (as we could see from https://github.com/trainline/webpack-bundle-delta/releases/tag/0.1.2) where @santino made the note about why the change occurred.

Adding "chores" would mean that the release process should be clearer for simple things like chores being merged and released.

**Comment by davidhouweling** [comment]
@santino do you agree with the above?

**Comment by santino** [comment]
Yes, this makes perfect sense.
Let me know if you're happy to look into this.

**Comment by davidhouweling** [comment]
After some digging, looks like we cannot presently do it: https://github.com/conventional-changelog/conventional-changelog/issues/696
