### ISSUE TITLE
Setup automated security audit

### ISSUE THREAD

**Issue by davidhouweling** [trainline/webpack-bundle-delta#11]
At present we don't have an automated security audit which could fix issues automatically from dependencies which might have security vulnerabilities.

GitHub has a [built in system using dependabot](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-dependabot-security-updates) or alternatively we can use a different tool such as [Snyk](https://snyk.io/) or [renovate](https://github.com/renovatebot/renovate).

Need to discuss here and then implement what we think is most appropriate.

Reference: #7

**Comment by davidhouweling** [comment]
@santino any strong feelings? I'm in favour of trying to get the native dependabot working just so we keep the repo as simple as possible, but would be good to have your thoughts.

Note: appropriate permissions are required to set up the security aspect (i believe).

**Comment by santino** [comment]
I was browsing through the settings and thinking about adding this in fact.
I think we start with built-in GitHub dependabot and see how it goes.

**Comment by santino** [comment]
I have activated this and it started raising PRs; so I'm going to close this issue :)
