### ISSUE TITLE
Improve GitHub workflow

### ISSUE THREAD

**Issue by davidhouweling** [trainline/webpack-bundle-delta#9]
The following improvements should be made to provide a more robust and verified package:

- Move linting to its own workflow: at present it lints for every build, but really we only need it to lint once, so would be better to move it to its own build pipelines to make the other ones a little faster
- Create integration pipelines:
  - at present we have build and test pipelines for each version of node we are supporting, but this doesn't actually prove it would be fully functional across the different operating systems
  - Windows is the notable one which may work differently than Mac and Linux, so having integration pipelines which run a set of integration tests across the varying node versions on each platform ensures that we don't miss any users (3 x 3)
  - This should be doable by creating a really basic integration test using the existing fixtures and the `local` command

**Comment by santino** [comment]
Good shout.
Linting step makes perfect sense and Windows pipelines would be a nice addition.
